import type { EntityIdentifier } from "@dataspecer/core/entity-model";
import type { ModelIdentifier } from "@dataspecer/core/model";

/** Identifies one independently clickable part of a diagram. */
export interface SvgLinkContext {
  /** Profiles use the same kind as the entity they specialize. */
  kind: "class" | "attribute" | "relationship" | "generalization" | "profile-link" | "diagram";
  /** Owning semantic model, or the represented model for a diagram node. */
  modelId: ModelIdentifier;
  /** Null for diagram references, which represent a model. */
  entityId: EntityIdentifier | null;
  /** The containing visual node for attributes; otherwise the visual element. */
  visualEntityId: EntityIdentifier;
}

/** Localizable annotations generated by the renderer. */
export interface SvgDiagramTexts {
  /** Prefix for the list of immediately profiled entities. */
  profileOf: string;
  /** Mandatory requirement-level heading. */
  mandatory: string;
  /** Recommended requirement-level heading. */
  recommended: string;
  /** Optional requirement-level heading. */
  optional: string;
  /** Heading when ordered attributes return to an unspecified requirement level. */
  undefinedLevel: string;
  /** Prefix for the model represented by a diagram-reference node. */
  represents: string;
}

/** Presentation options; all dimensions are in SVG user units. */
export interface SvgRenderOptions {
  /** Default: light. Explicit model colors are preserved in either theme. */
  theme?: "light" | "dark";
  /** A CSS color or "transparent". Omit to use the theme background. */
  background?: string;
  /** Outer canvas padding. Default: 20. */
  padding?: number;
  /** System sans-serif font size. Default: 16. */
  fontSize?: number;
  /** Preferred label language. Default: en. */
  language?: string;
  /** Namespace IRI to prefix. Supplied entries override the built-in prefixes. */
  prefixes?: Record<string, string>;
  /** Source of displayed names. Default: entity. */
  labelMode?: "entity" | "iri" | "vocabulary";
  /** Source model for header and edge colors. Default: entity. */
  colorMode?: "entity" | "vocabulary";
  /** Display of immediate profile targets. Default: label. */
  profileOfMode?: "label" | "iri" | "hidden";
  /** Include class IRI rows unless the title already shows the IRI. Default: true. */
  showIris?: boolean;
  /** Include attribute range labels and cardinalities. Default: true. */
  showRangeDetails?: boolean;
  /** Include attribute and relationship cardinalities. Default: true. */
  showCardinalities?: boolean;
  /** Override generated diagram annotations. */
  texts?: Partial<SvgDiagramTexts>;
  /** Called once per rendered element. Null leaves that element unlinked. */
  getLink?: (context: SvgLinkContext) => string | null;
  /** Browsing context for links. Default: _self. */
  linkTarget?: "_self" | "_blank";
  /** Receives unresolved references, unsupported elements, and rejected links. */
  onWarning?: (message: string) => void;
}

const prefixes: Record<string, string> = {
  "http://www.w3.org/2001/XMLSchema#": "xsd",
  "http://www.opengis.net/ont/geosparql#": "gsp",
  "http://www.opengis.net/ont/sf#": "sf",
  "http://www.w3.org/1999/02/22-rdf-syntax-ns#": "rdf",
  "http://www.w3.org/2000/01/rdf-schema#": "rdfs",
  "http://www.w3.org/ns/adms#": "adms",
  "http://www.w3.org/ns/dcat#": "dcat",
  "http://data.europa.eu/r5r/": "dcatap",
  "http://purl.org/dc/terms/": "dcterms",
  "http://xmlns.com/foaf/0.1/": "foaf",
  "http://www.w3.org/2002/07/owl#": "owl",
  "http://www.w3.org/ns/dx/prof/": "prof",
  "https://w3id.org/dsv-dap#": "dsv-dap",
  "https://w3id.org/dsv#": "dsv",
  "http://www.w3.org/2004/02/skos/core#": "skos",
  "https://mff-uk.github.io/specifications/dcat-dap/#": "dcat-dap",
  "https://mff-uk.github.io/specifications/dcat-ap/#": "dcat-ap",
  "https://ofn.gov.cz/dcat-ap-cz#": "dcat-ap-cz",
  "https://ofn.gov.cz/dcat-ap-cz-360-2023#": "dcat-ap-cz-360-2023",
  "https://slovník.gov.cz/veřejný-sektor/pojem/": "V-SGoV",
};

const english: SvgDiagramTexts = {
  profileOf: "profile of",
  mandatory: "<<mandatory>>", recommended: "<<recommended>>", optional: "<<optional>>",
  undefinedLevel: "<<undefined>>", represents: "Represents",
};

export type RenderOptions = ReturnType<typeof resolveOptions>;

/** Applies defaults and validates dimensions before any rendering begins. */
export function resolveOptions(options: SvgRenderOptions) {
  const fontSize = options.fontSize ?? 16;
  const padding = options.padding ?? 20;
  if (!Number.isFinite(fontSize) || fontSize <= 0 || !Number.isFinite(padding) || padding < 0) {
    throw new Error("SVG fontSize must be positive and padding non-negative; both must be finite.");
  }
  const dark = options.theme === "dark";
  const language = options.language ?? "en";
  return {
    ...options, fontSize, padding, language,
    background: options.background ?? (dark ? "#111827" : "#ffffff"),
    labelMode: options.labelMode ?? "entity",
    colorMode: options.colorMode ?? "entity",
    profileOfMode: options.profileOfMode ?? "label",
    showIris: options.showIris ?? true,
    showRangeDetails: options.showRangeDetails ?? true,
    showCardinalities: options.showCardinalities ?? true,
    linkTarget: options.linkTarget ?? "_self",
    onWarning: options.onWarning ?? ((message: string) => console.warn(message)),
    prefixes: { ...prefixes, ...options.prefixes },
    texts: {
      ...english,
      ...(language.split("-")[0] === "cs" ? {
        profileOf: "profiluje",
        mandatory: "<<povinné>>", recommended: "<<doporučené>>", optional: "<<volitelné>>",
        represents: "Reprezentuje",
      } : {}),
      ...options.texts,
    },
    palette: {
      body: dark ? "#1f2937" : "#ffffff",
      text: dark ? "#f9fafb" : "#000000",
      muted: dark ? "#9ca3af" : "#6b7280",
      border: dark ? "#d1d5db" : "#000000",
    },
  };
}
