#!/usr/bin/env node

// Generated by ChatGPT - https://chatgpt.com/share/699e27dd-6e40-8011-b825-2d808974612d

import * as path from "path";
import { stdin } from "process";
import * as YAML from "yaml";
import { GIT_REMOTE_CONFIGURATION_IRI } from "../../git-remote-configuration.ts";

// ---- Helper: Read from stdin ----
function readStdin(): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = "";

    stdin.setEncoding("utf8");

    stdin.on("data", chunk => {
      data += chunk;
    });

    stdin.on("end", () => {
      resolve(data);
    });

    stdin.on("error", err => {
      reject(err);
    });
  });
}

// ---- Helper: Get nested field safely ----
function getNestedField(obj: any, fieldPath: string): any {
  return fieldPath.split(".").reduce((acc, key) => {
    if (acc && typeof acc === "object") {
      return acc[key];
    }
    return undefined;
  }, obj);
}

// ---- Main ----
async function main() {
  const filename = process.argv[2];

  if (!filename) {
    console.error("Usage: cat file.json | node dist/index.js <filename>");
    process.exit(1);
  }

  const ext = path.extname(filename).toLowerCase();

  const input = await readStdin();

  let parsed: any;

  try {
    if (ext === ".json") {
      parsed = JSON.parse(input);
    } else if (ext === ".yaml" || ext === ".yml") {
      parsed = YAML.parse(input);
    } else {
      console.error("Unsupported file format. Use .json or .yaml/.yml");
      process.exit(1);
    }
  } catch (err) {
    console.error("Failed to parse file:", err);
    process.exit(1);
  }

  // Change this to whatever field you want
  const fieldPath = `configuration.${GIT_REMOTE_CONFIGURATION_IRI}.publicationBranch`;

  const value = getNestedField(parsed, fieldPath);

  if (value === undefined) {
    console.error(`Field "${fieldPath}" not found.`);
    process.exit(1);
  }

  process.stdout.write(String(value));
}

main();