#!/usr/bin/env node

// Generated by ChatGPT (with small touchups) - https://chatgpt.com/share/699eba97-c1c4-8011-bc3a-cc4cee2e8eeb

import * as fs from "fs";
import * as path from "path";
import YAML from "yaml";
import { GIT_REMOTE_CONFIGURATION_IRI } from "../../git-remote-configuration.ts";

/**
 * Usage:
 *   ts-node config-reader.ts <directory>
 */

async function main() {
  process.stdout.write(String("Test value\n"));
  // const directory = process.argv[2];

  // if (!directory) {
  //   console.error("Usage: config-reader <directory>");
  //   process.exit(1);
  // }

  // const files = fs.readdirSync(directory);

  // const metaFile = files.find(file =>
  //   file.startsWith(".meta") &&
  //   (file.endsWith(".json") || file.endsWith(".yaml") || file.endsWith(".yml"))
  // );

  // if (!metaFile) {
  //   console.error("No .meta file found");
  //   process.exit(1);
  // }

  // const fullPath = path.join(directory, metaFile);
  // const fileContent = fs.readFileSync(fullPath, "utf8");

  // let parsed: any;

  // if (metaFile.endsWith(".json")) {
  //   parsed = JSON.parse(fileContent);
  // } else {
  //   parsed = YAML.parse(fileContent);
  // }

  // const fieldValue = parsed["configuration"][GIT_REMOTE_CONFIGURATION_IRI]["publicationBranch"];
  // if (fieldValue === undefined) {
  //   console.error(`Field not found`);
  //   process.exit(1);
  // }

  // // Print ONLY the value so GitHub Actions can capture it cleanly
  // process.stdout.write(String(fieldValue));
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});