#!/usr/bin/env node

// Generated by ChatGPT (with small touchups) - https://chatgpt.com/share/699eba97-c1c4-8011-bc3a-cc4cee2e8eeb

import * as fs from "fs";
import * as path from "path";
import YAML from "yaml";
import { GIT_REMOTE_CONFIGURATION_IRI } from "../../git-remote-configuration.ts";
import { PUBLICATION_BRANCH_DEFAULT_NAME } from "../../git-provider-api.ts";

/**
 * Usage:
 *   ts-node config-reader.ts <directory>
 */

async function main() {
  const directory = process.argv[2];

  if (!directory) {
    console.error("Usage: config-reader <directory>");
    process.exit(1);
  }

  const files = fs.readdirSync(directory);

  const metaFile = files.find(file =>
    file.startsWith(".model") &&
    (file.endsWith(".json") || file.endsWith(".yaml") || file.endsWith(".yml"))
  );

  if (!metaFile) {
    console.error("No .meta file found");
    process.exit(1);
  }

  const fullPath = path.join(directory, metaFile);
  const fileContent = fs.readFileSync(fullPath, "utf8");

  let parsed: any;

  if (metaFile.endsWith(".json")) {
    parsed = JSON.parse(fileContent);
  } else {
    parsed = YAML.parse(fileContent);
  }

  console.info(parsed);
  const fieldValue = parsed["configuration"][GIT_REMOTE_CONFIGURATION_IRI]["publicationBranch"] ?? PUBLICATION_BRANCH_DEFAULT_NAME;

  // Print ONLY the value so GitHub Actions can capture it cleanly
  process.stdout.write(String(fieldValue) + "\n");
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});