import { EntityModel } from "@dataspecer/core-v2";
import { VisualModel } from "@dataspecer/visual-model";
import {
  type BaseEntityProfileDialogState,
  createEditBaseEntityProfileDialogState,
  createNewBaseEntityProfileDialogState,
} from "../base-entity-profile/base-entity-profile-dialog-state";
import {
  type EntityRepresentative,
  listClassToProfilesFromTracker,
  listClassToSpecializeFromTracker,
  representUndefinedClass,
} from "../utilities/dialog-utilities";
import { DialogSemanticTracker } from "../dialog-semantic-tracker";
import { EntityDsIdentifier } from "../../dataspecer/entity-model";
import { InMemorySemanticModel } from "@dataspecer/core-v2/semantic-model/in-memory";
import { semanticModelTrackerToCmeSemanticModel } from "../../dataspecer/cme-model/adapter";
import { configuration } from "../../application";
import { LabelResolver } from "../../dependency-tracker";
import { SemanticModelClassProfile } from "@dataspecer/core-v2/semantic-model/profile/concepts";
import { CmeClassProfileRole } from "@/dataspecer/cme-model/model";

export interface ClassProfileDialogState
  extends BaseEntityProfileDialogState<EntityRepresentative> {

  availableRoles: {

    value: string;

    label: string;

    cme: CmeClassProfileRole | null;

  }[];

  role: string;

}

const ROLES = [{
  value: "undefined",
  label: "class-profile.role.undefined",
  cme: null,
}, {
  value: "main",
  label: "class-profile.role.main",
  cme: CmeClassProfileRole.Main,
}, {
  value: "supportive",
  label: "class-profile.role.supportive",
  cme: CmeClassProfileRole.Supportive,
}];

export function createNewProfileClassDialogState(
  visualModel: VisualModel | null,
  language: string,
  profilesIdentifiers: EntityDsIdentifier[],
  tracker: DialogSemanticTracker,
  labelResolver: LabelResolver,
): ClassProfileDialogState {

  const allModels = semanticModelTrackerToCmeSemanticModel(
    tracker.semanticModels, visualModel,
    configuration().defaultModelColor);

  const noProfile = representUndefinedClass();

  const allProfiles = listClassToProfilesFromTracker(tracker, labelResolver);

  const allSpecializations = listClassToSpecializeFromTracker(tracker, labelResolver);

  // EntityProfileState

  const entityProfileState = createNewBaseEntityProfileDialogState(
    language, configuration().languagePreferences, allModels,
    allProfiles, profilesIdentifiers, noProfile, allSpecializations,
    configuration().classNameToIri);

  return {
    ...entityProfileState,
    isIriAutogenerated: true,
    // Role
    availableRoles: ROLES,
    role: ROLES[0].value
  };
}

/**
 * @throws InvalidState
 */
export function createEditClassProfileDialogState(
  visualModel: VisualModel | null,
  language: string,
  model: InMemorySemanticModel,
  entity: SemanticModelClassProfile,
  entityModels: Map<string, EntityModel>,
  tracker: DialogSemanticTracker,
  labelResolver: LabelResolver,
): ClassProfileDialogState {

  const allModels = semanticModelTrackerToCmeSemanticModel(
    tracker.semanticModels, visualModel,
    configuration().defaultModelColor);

  const noProfile = representUndefinedClass();

  const allProfiles = listClassToProfilesFromTracker(tracker, labelResolver)
    .filter(item => item.identifier !== entity.id);

  const allSpecializations = listClassToSpecializeFromTracker(tracker, labelResolver);

  // EntityProfileState

  const entityProfileState = createEditBaseEntityProfileDialogState(
    language, entityModels, allModels,
    { identifier: entity.id, model: model.getId() },
    allProfiles, entity.profiling, noProfile,
    entity.iri ?? "",
    entity.name, entity.nameFromProfiled,
    entity.description, entity.descriptionFromProfiled,
    entity.externalDocumentationUrl ?? "",
    entity.usageNote, entity.usageNoteFromProfiled,
    allSpecializations,
    entity.order ?? "");

  return {
    ...entityProfileState,
    // Role
    availableRoles: ROLES,
    role: ROLES.find(item => entity.tags?.includes(item.cme ?? ""))?.value
      ?? ROLES[0].value,
  };
}
