import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDirectory, '..');
const assetsRoot = join(packageRoot, 'assets', 'generated-app');
const templatesRoot = join(assetsRoot, 'templates');
const staticRoot = join(assetsRoot, 'static');
const outputPath = join(packageRoot, 'src', 'generated', 'generated-app-assets.ts');

const templates = readAssetMap(templatesRoot);
const staticFiles = readAssetMap(staticRoot);

const rawContent = [
    '// This file is generated by scripts/compile-assets.mjs.',
    '// Do not edit directly; edit assets/generated-app instead.',
    '',
    `export const generatedAppTemplates = ${formatRecord(templates)} as const;`,
    '',
    `export const generatedAppStaticFiles = ${formatRecord(staticFiles)} as const;`,
    '',
].join('\n');
const prettierOptions = (await prettier.resolveConfig(outputPath)) ?? {};
const content = await prettier.format(rawContent, {
    ...prettierOptions,
    filepath: outputPath,
});

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, content, 'utf8');

function readAssetMap(root) {
    return Object.fromEntries(
        collectFiles(root).map((filePath) => [
            toPosixPath(relative(root, filePath)),
            readFileSync(filePath, 'utf8'),
        ])
    );
}

function collectFiles(directory) {
    return readdirSync(directory, { withFileTypes: true })
        .flatMap((entry) => {
            const entryPath = join(directory, entry.name);
            return entry.isDirectory() ? collectFiles(entryPath) : [entryPath];
        })
        .sort((left, right) => left.localeCompare(right));
}

function formatRecord(record) {
    const entries = Object.entries(record);
    if (entries.length === 0) {
        return '{}';
    }

    return `{\n${entries
        .map(([key, value]) => `  ${toTsString(key)}: ${toTsString(value)},`)
        .join('\n')}\n}`;
}

function toTsString(value) {
    return `'${value
        .replaceAll('\\', '\\\\')
        .replaceAll("'", "\\'")
        .replaceAll('\r', '\\r')
        .replaceAll('\n', '\\n')
        .replaceAll('\u2028', '\\u2028')
        .replaceAll('\u2029', '\\u2029')}'`;
}

function toPosixPath(path) {
    return path.split(sep).join('/');
}
