import { BetterModalProps } from "@/lib/better-modal";
import { EditableType, getEditableAndNonEditableValue } from "@dataspecer/git";
import { Modal, ModalContent, ModalFooter, ModalHeader, ModalTitle } from "../components/modal";
import { Button } from "../components/ui/button";

type SvgVisualDiffDialogProps = {
  mergeFromSvg: string;
  mergeToSvg: string;
  editableType: EditableType;
} & BetterModalProps<null>


/**
 * Dialog that gets two svgs and the order (given by editableType). Shows the two svgs in the correct order next to each other (horizontally - left/right).
 */
const SvgVisualDiffDialog = ({ mergeFromSvg, mergeToSvg, editableType, isOpen, resolve }: SvgVisualDiffDialogProps) => {
  const { nonEditable: leftSvg, editable: rightSvg } = getEditableAndNonEditableValue(editableType, mergeFromSvg, mergeToSvg);


  return (
    <Modal open={isOpen} onClose={() => resolve(null)}>
        <ModalContent className="max-w-[90%]!">
          <ModalHeader>
            <ModalTitle>The visual diff of SVGs</ModalTitle>
          </ModalHeader>

          <div className="flex flex-1 flex-row">
            <SvgImage svgString={leftSvg} />
            <div className="border-l border-gray-400" />
            <SvgImage svgString={rightSvg} />
          </div>

          <ModalFooter>
            <Button variant="outline" onClick={() => resolve(null)}>Close</Button>
          </ModalFooter>
        </ModalContent>
    </Modal>
  );
};

/**
 * Core functionality generated by ChatGPT
 */
function SvgImage(props: { svgString: string }) {
  const encoded = encodeURIComponent(props.svgString)
    // Ensure proper XML/SVG encoding for special characters
    .replace(/'/g, "%27")
    .replace(/"/g, "%22");

  const dataUrl = `data:image/svg+xml,${encoded}`;

  return <div className="flex-1 overflow-auto p-2">
    <img src={dataUrl} alt="SVG" />
  </div>
}


/**
 * Generated by chatGPT
 * @deprecated TODO: Not used - I am not sure about this - I don't want to write sanitization - probably remove in favor of putting svg data into url and using <img>
 *
 */
// @ts-ignore
function SvgRenderer(props: { svgString: string }) {
  return (
    <div
      dangerouslySetInnerHTML={{ __html: props.svgString }}
    />
  );
}


export default SvgVisualDiffDialog;
