import { EntityModel } from "@dataspecer/core-v2";
import {
  type BaseEntityProfileDialogState,
  createEditBaseEntityProfileDialogState,
  createNewBaseEntityProfileDialogState,
} from "../base-entity-profile/base-entity-profile-dialog-state";
import {
  type BaseRelationshipProfileDialogState,
  createBaseRelationshipProfileDialogState,
} from "../base-relationship-profile/base-relationship-profile-dialog-state";
import {
  type EntityRepresentative,
  filterByModel,
  listAssociationsToProfileFromTracker,
  listAssociationsToSpecializeFromTracker,
  listRelationshipProfileDomainsFromTracker,
  type RelationshipRepresentative,
  representOwlThing,
  representRdfsLiteral,
  representUndefinedAssociation,
  representUndefinedClassProfile,
  sortRepresentatives,
} from "../utilities/dialog-utilities";
import { DialogSemanticTracker } from "../dialog-semantic-tracker";
import { VisualModel } from "@dataspecer/visual-model";
import { EntityDsIdentifier } from "../../dataspecer/entity-model";
import { semanticModelTrackerToCmeSemanticModel } from "../../dataspecer/cme-model/adapter";
import { configuration, createLogger } from "../../application";
import { LabelResolver } from "../../dependency-tracker";
import { InMemorySemanticModel } from "@dataspecer/core-v2/semantic-model/in-memory";
import { InvalidState } from "../../application/error";
import { getDomainAndRange } from "../../util/relationship-utils";
import { SemanticModelRelationshipProfile } from "@dataspecer/core-v2/semantic-model/profile/concepts";

const LOG = createLogger(import.meta.url);

export interface AssociationProfileDialogState extends
  BaseEntityProfileDialogState<RelationshipRepresentative>,
  BaseRelationshipProfileDialogState<EntityRepresentative> { }

/**
 * State represents a newly created profile for given profiled entity.
 */
export function createNewAssociationProfileDialogState(
  visualModel: VisualModel | null,
  language: string,
  profilesIdentifiers: EntityDsIdentifier[],
  tracker: DialogSemanticTracker,
  labelResolver: LabelResolver,
): AssociationProfileDialogState {

  const allModels = semanticModelTrackerToCmeSemanticModel(
    tracker.semanticModels, visualModel,
    configuration().defaultModelColor);

  const noProfile = representUndefinedAssociation();

  const owlThing = representOwlThing();
  const rdfsLiteral = representRdfsLiteral();

  const allProfiles = listAssociationsToProfileFromTracker(
    tracker, owlThing.identifier, rdfsLiteral.identifier, labelResolver);
  sortRepresentatives(allProfiles);

  const allDomains = listRelationshipProfileDomainsFromTracker(tracker, labelResolver);
  sortRepresentatives(allDomains);

  const allRanges = allDomains;

  const allSpecializations = listAssociationsToSpecializeFromTracker(
    tracker, owlThing.identifier, rdfsLiteral.identifier, labelResolver);

  // EntityProfileState

  const entityProfileState = createNewBaseEntityProfileDialogState(
    language, configuration().languagePreferences,
    allModels,
    allProfiles, profilesIdentifiers, noProfile, allSpecializations,
    configuration().relationshipNameToIri);

  // RelationshipState<EntityRepresentative>

  const profile = entityProfileState.profiles[0];
  const relationshipProfileState = createBaseRelationshipProfileDialogState(
    entityProfileState.model,
    allModels,
    profile.domain, profile.domainCardinality.cardinality, allDomains,
    filterByModel, representUndefinedClassProfile(),
    profile.range, profile.rangeCardinality.cardinality, allRanges,
    filterByModel, representUndefinedClassProfile(),
    []
  );

  const result = {
    ...entityProfileState,
    ...relationshipProfileState,
    isIriAutogenerated: true,
  };

  return configuration().relationshipProfileToIri(result);
}

/**
 * @throws {InvalidState}
 */
export function createEditAssociationProfileDialogState(
  visualModel: VisualModel | null,
  language: string,
  model: InMemorySemanticModel,
  rawEntity: SemanticModelRelationshipProfile,
  aggregatedEntity: SemanticModelRelationshipProfile,
  entityModels: Map<string, EntityModel>,
  tracker: DialogSemanticTracker,
  labelResolver: LabelResolver,
): AssociationProfileDialogState {

  const { domain, range } = getDomainAndRange(rawEntity);

  const { domain: aggregatedDomain, range: aggregatedRange } =
    getDomainAndRange(aggregatedEntity);

  if (domain === null || range === null
    || aggregatedDomain === null || aggregatedRange === null) {
    LOG.error("Entity has invalid ends.",
      { domain, range, aggregatedDomain, aggregatedRange });
    throw new InvalidState();
  }

  //

  const allModels = semanticModelTrackerToCmeSemanticModel(
    tracker.semanticModels, visualModel,
    configuration().defaultModelColor);

  const noProfile = representUndefinedAssociation();

  const owlThing = representOwlThing();
  const rdfsLiteral = representRdfsLiteral();

  const allProfiles = listAssociationsToProfileFromTracker(
    tracker, owlThing.identifier, rdfsLiteral.identifier, labelResolver);
  sortRepresentatives(allProfiles);

  const allDomains = listRelationshipProfileDomainsFromTracker(tracker, labelResolver);
  sortRepresentatives(allDomains);

  const allRanges = allDomains;

  const allSpecializations = listAssociationsToSpecializeFromTracker(
    tracker, owlThing.identifier, rdfsLiteral.identifier, labelResolver);

  // EntityProfileState

  const entityProfileState = createEditBaseEntityProfileDialogState(
    language, entityModels, allModels,
    { identifier: rawEntity.id, model: model.getId() },
    allProfiles, range.profiling, noProfile, range.iri ?? "",
    range.name, range.nameFromProfiled,
    range.description, range.descriptionFromProfiled,
    range.externalDocumentationUrl ?? "",
    range.usageNote, range.usageNoteFromProfiled,
    allSpecializations);

  // RelationshipState<EntityRepresentative>

  const relationshipProfileState = createBaseRelationshipProfileDialogState(
    entityProfileState.model,
    allModels,
    domain.concept, domain.cardinality, allDomains,
    filterByModel, representUndefinedClassProfile(),
    range.concept, range.cardinality, allRanges,
    filterByModel, representUndefinedClassProfile(),
    range.tags ?? [],
  );

  return {
    ...entityProfileState,
    ...relationshipProfileState,
  };

}
