// Boilerplate generated by ChatGPT we added steps actions

import { driver as createDriver } from "driver.js";
import "driver.js/dist/driver.css";
import { TFunction } from "i18next";

/**
 * Starts a simple guided tour for the diff editor dialog.
 * This is an example of how Driver.js can be used in the manager application.
 */
export function startDiffEditorDialogTour(t: TFunction<"translation", undefined>, onDestroyed?: () => void): void {
  const driver = createDriver({
    overlayClickBehavior: "close",
    nextBtnText: "Next",
    prevBtnText: "Back",
    doneBtnText: "Done",
    animate: true,
    overlayOpacity: 0.5,
    disableActiveInteraction: true,
    onDestroyed: () => {
      onDestroyed?.();
    },
    steps: [
    {
      element: "#directory-diff-tour-panel",
      popover: {
        title: "You are in diff editor (You can use left and right arrows to step in the tutorial)",
        description: t("git.diff-editor.more-detail.line.two"),
      },
    },
    {
      element: "#root-package-project-iriroot-package-iri-datastore-0-meta-json-new",
      popover: {
        title: "Datastore",
        description: "Packages/models consist of datastores",
      },
      // onHighlighted: (element) => {    // To highlight the line, but we do not want that
      //   (element as HTMLButtonElement)?.click()
      // }
    },
    {
      element: "#diff-editor-branch-names-tour-left",
      popover: {
        title: "Left branch - the incoming changes",
        description: "The '(Git)' means that the content comes from Git - It matches the corresponding Git commit and is read-only",
      },
    },
        {
      element: "#diff-editor-branch-names-tour-right",
      popover: {
        title: "Right branch - the branch being modified",
        description: "If there is no '(Git)' then the content comes from Dataspecer data specification",
      },
    },
    {
      element: "#diff-editor-parent-div",
      popover: {
        title: "The diff text editor",
        description: "Both windows of diff editor are unchanged at the time of creation of the merge state",
      },
    },
    {
      element: "#diff-editor-parent-left-half-div",
      popover: {
        title: "The left part of window is always non-editable",
        description: "",
      },
    },
    {
      element: "#diff-editor-parent-right-half-div",
      popover: {
        title: "The right part of window is editable",
        description: "",
      },
    },
    {
      element: "#diff-editor-tree-panel",
      popover: {
        title: "This is the diff tree with packages/models and the datastores",
        description: "",
      },
    },
    {
      element: "#root-package-project-iri-new",
      popover: {
        title: "Package",
        description: "Or model - the type is indicated by the icon.",
      },
    },
    {
      element: "#root-package-project-iriroot-package-iri-datastore-0-meta-json-new",
      popover: {
        title: "Datastore",
        description: "Packages/models consist of datastores",
      },
    },
    {
      element: "#root-package-project-iriroot-package-iri-datastore-0-meta-json-new-resolve-icon",
      popover: {
        title: "Conflicts",
        description: "This icon marks the fact that datastore between the two sources contain conflicts",
      },
    },
    {
      element: "#root-package-project-iriroot-package-iri-datastore-0-meta-json-new-resolve-button2",
      popover: {
        title: "Resolve button",
        description: "This is the resolve button for datastore. Clicking it, marks the conflict as resolved.",
      },
    },
    {
      element: "#root-package-project-iri-new-resolve-button1",
      popover: {
        title: "Resolve button for packages/models",
        description: "You can also click the resolve button on package/model to mark all underlying conflicts as resolved.",
      },
    },
    {
      element: "#root-package-project-iriroot-package-iri-datastore-0-meta-json-new-resolve-icon",
      popover: {
        title: "Icon after marking as resolved",
        description: "",
      },
      onHighlighted: (_element) => {
        const element = document.getElementById("root-package-project-iri-new-resolve-button1");
        (element as HTMLButtonElement)?.click();
      }
    },
    {
      element: "#root-package-project-iriroot-package-iri-datastore-0-meta-json-new-in-cache",
      popover: {
        title: "Icon that shows that the datastore is in cache",
        description: "Those datastores will be saved to backend on 'save' action",
      },
    },
    {
      element: "#root-package-project-iri-root-package-project-iri-underroot-package-iri-under-datastore-0-meta-json-new",
      popover: {
        title: "Black means unchanged",
        description: "",
      },
    },
    {
      element: "#root-package-project-iriroot-package-iri-datastore-0-meta-json-new",
      popover: {
        title: "Blue means modified",
        description: "",
      },
    },
    {
      element: "#root-package-project-iri-root-package-project-iri-under-root-package-project-iri-file-node-underroot-package-iri-file-node-under-datastore-0-meta-json-new",
      popover: {
        title: "Green means present only in right window",
        description: "The colors are always in the relation to the 'right' window",
      },
    },
    {
      element: "#root-package-project-iri-root-package-project-iri-under-root-package-project-iri-file-node-underroot-package-iri-file-node-under-datastore-0-meta-json-new-remove-datastore-button",
      popover: {
        title: "You can remove the green nodes from Dataspecer data specification",
        description: "This kind of action is irreversible after you save the changes with the 'Save' or 'Finalize' button.",
      },
    },
    {
      element: "#root-package-project-iri-root-package-project-iri-under-root-package-project-iri-under-under-root-package-project-iri-file-node-under-underroot-package-iri-file-node-under-under-datastore-0-meta-json-new",
      popover: {
        title: "Red means present only in left window",
        description: "",
      },
    },
    {
      element: "#root-package-project-iri-root-package-project-iri-under-root-package-project-iri-under-under-root-package-project-iri-file-node-under-underroot-package-iri-file-node-under-under-datastore-0-meta-json-new-create-datastore-button",
      popover: {
        title: "You can add the missing (red) datastore to Dataspecer",
        description: "",
      },
    },
    {
      element: "#diff-editor-prev-diff",
      popover: {
        title: "Previous diff",
        description: "Use this button to move to the previous diff in the current file.",
      },
    },
    {
      element: "#diff-editor-next-diff",
      popover: {
        title: "Next diff",
        description: "Use this button to move to the next diff in the current file.",
      },
    },
    {
      element: "#diff-editor-show-stripped-version",
      popover: {
        title: "Toggle between stripped and raw version",
        description: "Just keep it on. The stripped version hides unique lines that are not related to the data specification data.",
      },
    },
    {
      element: "#diff-editor-save-all-button",
      popover: {
        title: "Save changes",
        description: "Save your current diff edits to the backend.",
      },
    },
    {
      element: "#diff-editor-finalize-button",
      popover: {
        title: "After you mark all conflicts as resolved finalize merge state",
        description: "Saves your changes and after that finalizes the merge state by peforming corresponding actions.",
      },
    }
  ]
  });

  driver.drive();
}
