// Boilerplate generated by ChatGPT we added steps actions

import { driver as createDriver, DriveStep } from "driver.js";
import "driver.js/dist/driver.css";
import { TFunction } from "i18next";
import { Dispatch, SetStateAction } from "react";


/**
 * Starts a simple guided tour for the Git related functionality in the manager application.
 */
export function startGitManagerInitialTour(_t: TFunction<"translation", undefined>, setTourStep: Dispatch<SetStateAction<number>>, onDestroyed?: () => void): void {
  const getTourId = (element: string) => `#${element}-1`;

  const tourSteps: DriveStep[] = [
    {
      element: getTourId("manager-git-unique-iri-label"),
      popover: {
        title: "This tour will guide you through Git related functionality ",
        description: "You can use left and right arrow to navigate through steps.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-unique-iri-label"),
      popover: {
        title: "Resource IRI",
        description: "The unique IRI of the resource.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-project-iri-label"),
      popover: {
        title: "Project IRI",
        description: "The unique IRI of resource within Git repository.<br/><br/>If resources have the same project IRI, they represent the same resource within repository.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-branch-label"),
      popover: {
        title: "Git branch",
        description: "The represented Git branch.<br/><br/>Note that the branch does not have to exist on remote.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-status-indicator"),
      popover: {
        title: "Git status",
        description: "If present, the data specification is linked to a Git repository.<br/><br/>On click redirects to remote Git repository.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-status-indicator"),
      popover: {
        title: "Git status tooltip",
        description: "Pointing at the 'Git' renders the tooltip seen at right.",
      },
      onHighlighted: () => {},
    },
    {
      element: "#git-tooltip-manager-has-uncommitted-changes",
      popover: {
        title: "Uncommitted changes",
        description: "Indicates whether the dataspec has local not yet committed changes.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-tour-git-verify-changes"),
      popover: {
        title: "Verify changes",
        description: "If you undid all changes, click this button.<br/><br/>It validates whether the dataspec really has uncommitted changes.",
      },
      onHighlighted: () => {},
    },
    {
      element: "#git-tooltip-manager-active-merge-state-count",
      popover: {
        title: "Merge state count",
        description: "Shows how many merge states are currently active for this resource.<br/><br/>Merge states are explained in a separate tour together with Git actions.",
      },
      onHighlighted: () => {},
    },
    {
      element: "#git-tooltip-manager-project-iri",
      popover: {
        title: "Full project IRI",
        description: "Explained earlier.",
      },
      onHighlighted: () => {},
    },
    {
      element: "#git-tooltip-manager-type",
      popover: {
        title: "Branch or commit",
        description: "Whether the dataspec represents a branch head or a specific commit.",
      },
      onHighlighted: () => {},
    },
    {
      element: "#git-tooltip-manager-tracked-commit-hash",
      popover: {
        title: "Tracked commit hash",
        description: "Displays the shortened commit hash that this dataspec represents.<br/><br/>It moves once you pull/commit changes.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-status-indicator"),
      popover: {
        title: '<span style="color:green">Green</span> Git status',
        description: "Dataspec is up-to-date with the remote.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-status-indicator"),
      popover: {
        title: '<span style="color:yellow">Yellow</span> Git status',
        description: "Dataspec has uncommitted changes.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-git-status-indicator"),
      popover: {
        title: '<span style="color:red">Red</span> Git status',
        description: "Dataspec has open merge state that need to be resolved.",
      },
      onHighlighted: () => {},
    },
  ];

  const driver = createDriver({
    overlayClickBehavior: "close",
    nextBtnText: "Next",
    prevBtnText: "Back",
    doneBtnText: "Done",
    animate: true,
    overlayOpacity: 0.5,
    disableActiveInteraction: false,
    onDestroyed: () => {
      onDestroyed?.();
    },
    steps: tourSteps,
    onPrevClick: (_step) => {
      setTourStep((prev) => prev - 1);
      driver.movePrevious();
    },
    onNextClick: (_step) => {
      setTourStep((prev) => prev + 1);
      driver.moveNext();
    },
  });

  driver.drive();
}
