// Boilerplate generated by ChatGPT we added steps actions

import { driver as createDriver, DriveStep } from "driver.js";
import "driver.js/dist/driver.css";
import { TFunction } from "i18next";
import { Dispatch, SetStateAction } from "react";


/**
 * Starts a simple guided tour for the Git related functionality in the manager application.
 */
export function startGitManagerMergeStatesAndGitActionsTour(_t: TFunction<"translation", undefined>, setTourStep: Dispatch<SetStateAction<number>>, onDestroyed?: () => void): void {
  const getTourId = (element: string) => `#${element}-1`;

  const tourSteps: DriveStep[] = [
    {
      popover: {
        title: "This tour will explain merge states and related Git actions",
        description: "You can use left and right arrow to navigate through steps.",
      },
      onHighlighted: () => {},
    },
    {
      popover: {
        title: 'Merge states',
        description: "Merge state marks the fact that the Git operation has conflicts that need to be resolved.<br/><br/>Merge states can be created by the following actions.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-tour-git-action-commit-item"),
      popover: {
        title: "Commit",
        description: "Commit your local changes to remote.<br/><br/>If the dataspec does not track latest commit a merge state will be created.",
      },
      onHighlighted: (e?: Element) => {console.info({e})},
    },
    {
      element: getTourId("manager-tour-git-action-pull-item"),
      popover: {
        title: "Pull",
        description: "Pull the latest changes from the remote repository.<br/><br/>If the dataspec contains changes compared to tracked commit a merge state will be created.<br/>Otherwise, the dataspec will be updated with the data from remote.",
      },
      onHighlighted: (e?: Element) => {console.info({e})},
    },
    {
      element: getTourId("manager-tour-git-merge-item"),
      popover: {
        title: "Merge",
        description: "Always creates a merge state between two chosen dataspec branches.",
      },
      onHighlighted: () => {},
    },
    {
      element: getTourId("manager-tour-git-show-merge-states-item"),
      popover: {
        title: "Resolve merge states",
        description: "You can view and resolve the merge states here.",
      },
      onHighlighted: () => {},
    },
  ];

  const driver = createDriver({
    overlayClickBehavior: "close",
    nextBtnText: "Next",
    prevBtnText: "Back",
    doneBtnText: "Done",
    animate: true,
    overlayOpacity: 0.5,
    disableActiveInteraction: false,
    onDestroyed: () => {
      onDestroyed?.();
    },
    steps: tourSteps,
    onPrevClick: (_step) => {
      setTourStep((prev) => prev - 1);
      driver.movePrevious();
    },
    onNextClick: (_step) => {
      setTourStep((prev) => prev + 1);
      driver.moveNext();
    },
  });

  driver.drive();
}
