export enum ViolationCode {
  // Errors
  GenerateFormatFailed = 'GENERATE_FORMAT_FAILED',
  GenerateWriteFailed = 'GENERATE_WRITE_FAILED',
  GraphDuplicateDatasourceId = 'GRAPH_DUPLICATE_DATASOURCE_ID',
  GraphDuplicateEdgeId = 'GRAPH_DUPLICATE_EDGE_ID',
  GraphDuplicateNodeId = 'GRAPH_DUPLICATE_NODE_ID',
  GraphSyntaxInvalid = 'GRAPH_SYNTAX_INVALID',
  MetadataResolutionFailed = 'METADATA_RESOLUTION_FAILED',
  SemanticCannotCascadeAggregation = 'SEMANTIC_CANNOT_CASCADE_AGGREGATION',
  SemanticCascadeRequiresParentCascade = 'SEMANTIC_CASCADE_REQUIRES_PARENT_CASCADE',
  SemanticCircularComposition = 'SEMANTIC_CIRCULAR_COMPOSITION',
  SemanticConflictingAssociationKind = 'SEMANTIC_CONFLICTING_ASSOCIATION_KIND',
  SemanticConflictingRdfPropertyAlias = 'SEMANTIC_CONFLICTING_RDF_PROPERTY_ALIAS',
  SemanticDuplicateAggregateName = 'SEMANTIC_DUPLICATE_AGGREGATE_NAME',
  SemanticDuplicateGeneratedFieldName = 'SEMANTIC_DUPLICATE_GENERATED_FIELD_NAME',
  SemanticDuplicateRouteId = 'SEMANTIC_DUPLICATE_ROUTE_ID',
  SemanticInvalidDeletePolicy = 'SEMANTIC_INVALID_DELETE_POLICY',
  SemanticInvalidRedirect = 'SEMANTIC_INVALID_REDIRECT',
  SemanticInvalidTransition = 'SEMANTIC_INVALID_TRANSITION',
  SemanticMultipleRedirects = 'SEMANTIC_MULTIPLE_REDIRECTS',
  SemanticNestedAssociationRequiresComposition = 'SEMANTIC_NESTED_ASSOCIATION_REQUIRES_COMPOSITION',
  SemanticNoNodes = 'SEMANTIC_NO_NODES',
  SemanticRedirectRequiresSameClass = 'SEMANTIC_REDIRECT_REQUIRES_SAME_CLASS',
  SemanticRdfPropertyAliasConfigPath = 'SEMANTIC_RDF_PROPERTY_ALIAS_CONFIG_PATH',
  SemanticTransitionRequiresSameClass = 'SEMANTIC_TRANSITION_REQUIRES_SAME_CLASS',
  SemanticUnknownAggregate = 'SEMANTIC_UNKNOWN_AGGREGATE',
  SemanticUnknownEdgeSource = 'SEMANTIC_UNKNOWN_EDGE_SOURCE',
  SemanticUnknownEdgeTarget = 'SEMANTIC_UNKNOWN_EDGE_TARGET',
  SemanticUnsupportedDatasourceCount = 'SEMANTIC_UNSUPPORTED_DATASOURCE_COUNT',
  SemanticUnsupportedDatasourceType = 'SEMANTIC_UNSUPPORTED_DATASOURCE_TYPE',
  SemanticUnrecoverableSpecialization = 'SEMANTIC_UNRECOVERABLE_SPECIALIZATION',

  // Warnings
  SemanticAssociationConfigNotAllowed = 'SEMANTIC_ASSOCIATION_CONFIG_NOT_ALLOWED',
  SemanticAssociationPathNotAssociation = 'SEMANTIC_ASSOCIATION_PATH_NOT_ASSOCIATION',
  SemanticDeleteConfigNotAllowed = 'SEMANTIC_DELETE_CONFIG_NOT_ALLOWED',
  SemanticDeletePathNotAssociation = 'SEMANTIC_DELETE_PATH_NOT_ASSOCIATION',
  SemanticDuplicateEdge = 'SEMANTIC_DUPLICATE_EDGE',
  SemanticInvalidAssociationKind = 'SEMANTIC_INVALID_ASSOCIATION_KIND',
  SemanticNamedNodeIdentityOverride = 'SEMANTIC_NAMED_NODE_IDENTITY_OVERRIDE',
  SemanticRdfPropertyAliasesCoalesced = 'SEMANTIC_RDF_PROPERTY_ALIASES_COALESCED',
  SemanticTransitionRequiresAssociation = 'SEMANTIC_TRANSITION_REQUIRES_ASSOCIATION',
}
