// Generated by ChatGPT

import { ReactNode, useState, useEffect } from "react";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { GithubIcon } from "lucide-react";

interface Option<T = any> {
  key: ReactNode;
  value: T;
  tooltip?: string;
}

interface ComboBoxProps<T = any> {
  options: Option<T>[];
  onChange?: (value: T) => void;
  selectedValue?: T; // controlled mode
}

export const ComboBox = <T extends any>({
  options,
  onChange,
  selectedValue,
}: ComboBoxProps<T>) => {
  // Internal state for uncontrolled mode
  const [internalSelected, setInternalSelected] = useState<Option<T>>(options[0]);

  // Update internalSelected if controlled selectedValue changes
  useEffect(() => {
    if (selectedValue !== undefined) {
      const found = options.find((opt) => opt.value === selectedValue);
      if (found) setInternalSelected(found);
    }
  }, [selectedValue, options]);

  const handleSelect = (option: Option<T>) => {
    setInternalSelected(option); // Update internal state
    if (onChange) onChange(option.value);
  };

  const selectedOption = internalSelected;

  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger className="flex inline-flex justify-between items-center w-auto px-3 py-2 border border-gray-300 hover:bg-gray-200 rounded-md bg-white cursor-pointer focus:outline-none">
        <span>{selectedOption?.key}</span>
        {/* <span className="ml-2"><ChevronDown/></span> */}
      </DropdownMenu.Trigger>

      <DropdownMenu.Content className="min-w-[var(--radix-dropdown-menu-trigger-width)] mt-1 w-full border border-gray-300 rounded-md bg-white max-h-60 overflow-auto focus:outline-none">
        {options.map((option, idx) => (
          <DropdownMenu.Item
            key={idx}
            title={option.tooltip}
            onSelect={() => handleSelect(option)}
            className="px-3 py-2 cursor-pointer hover:bg-gray-100 focus:outline-none"
          >
            {option.key}
          </DropdownMenu.Item>
        ))}
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
};

/**
 *
 * @returns The key which is how it is rendered in the combobox and the value which is the URL to the Git Provider.
 *  The value should contain the schema and end with / - for example https://github.com/
 */
export function createGitProviderComboBoxOptions() {
  const gitProvidersComboBoxOptions = [
    {
      key: (
        <span className="flex items-center space-x-1">
          <span>GitHub</span>
          <GithubIcon className="w-4 h-4" />
        </span>
      ),
      value: "https://github.com/"
    },
  ];
  return gitProvidersComboBoxOptions;
}
