// Generated by ChatGPT

import { ReactNode, useState, useEffect } from "react";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { GithubIcon } from "lucide-react";
import { GitProviderEnum } from "@dataspecer/git";

interface Option<T = any> {
  key: ReactNode;
  value: T;
  tooltip?: string;
}

interface ComboBoxProps<T = any> {
  options: Option<T>[];
  onChange?: (value: T) => void;
  selectedValue?: T; // controlled mode
}

export const ComboBox = <T extends any>({
  options,
  onChange,
  selectedValue,
}: ComboBoxProps<T>) => {
  const [internalSelected, setInternalSelected] = useState<Option<T>>(options[0]);

  useEffect(() => {
    if (selectedValue !== undefined) {
      const found = options.find((opt) => opt.value === selectedValue);
      if (found) setInternalSelected(found);
    }
  }, [selectedValue, options]);

  const handleSelect = (option: Option<T>) => {
    setInternalSelected(option);
    if (onChange) onChange(option.value);
  };

  const selectedOption = internalSelected;

  return (
    <DropdownMenu.Root>
      <DropdownMenu.Trigger
        className="
          flex inline-flex justify-between items-center
          w-auto px-3 py-2 rounded-md cursor-pointer
          border
          bg-white text-gray-900 border-gray-300 hover:bg-gray-100
          dark:bg-gray-800 dark:text-gray-100 dark:border-gray-600 dark:hover:bg-gray-700
          focus:outline-none focus:ring-2 focus:ring-blue-500 dark:focus:ring-blue-400
        "
      >
        <span>{selectedOption?.key}</span>
      </DropdownMenu.Trigger>

      <DropdownMenu.Content
        className="
          min-w-(--radix-dropdown-menu-trigger-width)
          mt-1 w-full rounded-md border max-h-60 overflow-auto
          bg-white text-gray-900 border-gray-300
          dark:bg-gray-800 dark:text-gray-100 dark:border-gray-600
          shadow-md
          focus:outline-none
        "
      >
        {options.map((option, idx) => (
          <DropdownMenu.Item
            key={idx}
            title={option.tooltip}
            onSelect={() => handleSelect(option)}
            className="
              px-3 py-2 cursor-pointer
              hover:bg-gray-100
              dark:hover:bg-gray-700
              focus:outline-none
            "
          >
            {option.key}
          </DropdownMenu.Item>
        ))}
      </DropdownMenu.Content>
    </DropdownMenu.Root>
  );
};

type ProviderComboBoxType = { key: ReactNode, value: GitProviderEnum }[];

/**
 *
 * @returns The key which is how it is rendered in the combobox and the value which is the URL to the Git Provider.
 *  The value is the provider, which can be converted to the url using {@link getGitProviderDomain}.
 */
export function createGitProviderComboBoxOptions(): ProviderComboBoxType {
  const gitProvidersComboBoxOptions = [
    {
      key: (
        <span className="flex items-center space-x-1">
          <span>GitHub</span>
          <GithubIcon className="w-4 h-4" />
        </span>
      ),
      value: GitProviderEnum.GitHub,
    },
  ];
  return gitProvidersComboBoxOptions;
}
