// Generated by ChatGPT


import { ComparisonData } from "@dataspecer/git";
import React, { ReactNode, useState } from "react";
import { Button } from "./ui/button";

type ExpandableListProps = {
  title: string;
  items: ComparisonData[];
  buttonComponentContent: ReactNode;
  onClickAction: (comparisonData: ComparisonData) => void;
};

const ExpandableList: React.FC<ExpandableListProps> = ({ title, items, buttonComponentContent, onClickAction }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="w-96 border shadow p-2 bg-white">
      {/* Header */}
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className="flex justify-between items-center w-full text-left font-medium text-sm"
      >
        {title}
        <span className="text-gray-500">{isExpanded ? "▲" : "▼"}</span>
      </button>

      {/* Expandable content */}
      {isExpanded && (
        <ul className="mt-2 space-y-1 pl-4 list-disc text-gray-700 text-sm">
          {items.map((item, idx) => (
            <li key={idx}>
              {item.affectedDataStore.fullName}
              <Button onClick={() => onClickAction(item)} >
                {buttonComponentContent}
              </Button>
              </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default ExpandableList;
