// Generated by ChatGPT


import { ComparisonData } from "@dataspecer/git";
import React, { ReactNode, useState } from "react";

type ExpandableListProps = {
  title: string;
  items: ComparisonData[];
  buttonComponentContent: ReactNode;
  onClickAction: (comparisonData: ComparisonData) => void;
};

const ExpandableList: React.FC<ExpandableListProps> = ({ title, items, buttonComponentContent, onClickAction }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className="full-w border shadow p-2 bg-white">
      {/* Header */}
      <button
        onClick={() => setIsExpanded(!isExpanded)}
        className=""
      >
        {title}
        <span className="text-gray-500">{isExpanded ? "▲" : "▼"}</span>
      </button>

      {/* Expandable content */}
      {isExpanded && (
        <ul className="">
          {items.map((item, idx) => (
            <li key={idx} className="flex">
              {item.affectedDataStore.fullName}
              <button className="hover:bg-gray-300" onClick={() => onClickAction(item)} >
                {buttonComponentContent}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default ExpandableList;
