// React component generated by chatgpt

import { useTranslation } from "react-i18next";

export type ExportFormatType = "json" | "yaml";

type ExportFormatRadioButtonsProps = {
  exportFormat: ExportFormatType,
  setExportFormat: (newExportFormat: ExportFormatType) => void,
}

export const ExportFormatRadioButtons = (props: ExportFormatRadioButtonsProps) => {
  const { t } = useTranslation();

  return (
    <div className="mt-4 mb-4 flex items-center space-x-6">
      <span className="text-sm font-semibold">{t("git.choose-an-export-format")}:</span>

      <label className="flex items-center space-x-2 cursor-pointer">
        <input
          type="radio"
          value="json"
          checked={props.exportFormat === "json"}
          onChange={(e) => props.setExportFormat(e.target.value as ExportFormatType)}
          className="form-radio text-blue-600"
        />
        <span>JSON</span>
      </label>
      <label className="flex items-center space-x-2 cursor-pointer">
        <input
          type="radio"
          value="yaml"
          checked={props.exportFormat === "yaml"}
          onChange={(e) => props.setExportFormat(e.target.value as ExportFormatType)}
          className="form-radio text-blue-600"
        />
        <span>YAML</span>
      </label>
    </div>
  );
};