// React component generated by and later modified to fit our UI needs (tooltips and so on)

import { ExportFormatType } from "@dataspecer/git";
import { useTranslation } from "react-i18next";
import { PopOverGitGeneralComponent } from "./popover-git-general";


type ExportFormatRadioButtonsProps = {
  exportFormat: ExportFormatType,
  setExportFormat: (newExportFormat: ExportFormatType) => void,
}


/**
 * Similiar to {@link ExportVersionRadioButtons}, but here we let user choose the export version (currently JSON/YAML)
 */
export const ExportFormatRadioButtons = (props: ExportFormatRadioButtonsProps) => {
  const { t } = useTranslation();

  return (
    <div className="grid grid-cols-[1fr_1.5fr] mt-4 items-center justify-between space-x-6">
      <span className="flex flex-1 flex-row text-sm">{t("git.choose-an-export-format")}&nbsp;
        <div className="">
          <PopOverGitGeneralComponent>
            <RepositoryExportFormatTooltip/>
          </PopOverGitGeneralComponent>
        </div>
      </span>
      <div className="flex flex-1 flex-row pb-4">
        <label className="flex items-center space-x-2 pl-8">
          <input
            type="radio"
            value="json"
            checked={props.exportFormat === "json"}
            onChange={(e) => props.setExportFormat(e.target.value as ExportFormatType)}
            className="form-radio text-blue-600"
          />
          <span>JSON</span>
        </label>
        <label className="flex items-center space-x-2 pl-4">
          <input
            type="radio"
            value="yaml"
            checked={props.exportFormat === "yaml"}
            onChange={(e) => props.setExportFormat(e.target.value as ExportFormatType)}
            className="form-radio text-blue-600"
          />
          <span>YAML</span>
        </label>
      </div>
    </div>
  );
};


function RepositoryExportFormatTooltip() {
  const { t } = useTranslation();

  return <div>
    {t("git.export-format-tooltip.intro")}
    <br/>
    {t("git.export-format-tooltip.json")}
    <br/>
    {t("git.export-format-tooltip.yaml")}
    <br/>
    {t("git.export-format-tooltip.note")}
  </div>;
}
