// React component generated by and later modified to fit our UI needs (tooltips and so on)

import { ExportFormatType } from "@dataspecer/git";
import { useTranslation } from "react-i18next";
import { PopOverGitGeneralComponent } from "./popover-git-general";


type ExportFormatRadioButtonsProps = {
  exportFormat: ExportFormatType,
  setExportFormat: (newExportFormat: ExportFormatType) => void,
}

export const ExportFormatRadioButtons = (props: ExportFormatRadioButtonsProps) => {
  const { t } = useTranslation();

  return (
    <div className="grid grid-cols-[1fr_1.5fr] mt-4 items-center justify-between space-x-6">
      <span className="flex flex-1 flex-row text-sm">{t("git.choose-an-export-format")}&nbsp;
        <div className="">
          <PopOverGitGeneralComponent>
            <RepositoryExportFormatTooltip/>
          </PopOverGitGeneralComponent>
        </div>
      </span>
      <div className="flex flex-1 flex-row pb-4">
        <label className="flex items-center space-x-2 pl-8">
          <input
            type="radio"
            value="json"
            checked={props.exportFormat === "json"}
            onChange={(e) => props.setExportFormat(e.target.value as ExportFormatType)}
            className="form-radio text-blue-600"
          />
          <span>JSON</span>
        </label>
        <label className="flex items-center space-x-2 pl-4">
          <input
            type="radio"
            value="yaml"
            checked={props.exportFormat === "yaml"}
            onChange={(e) => props.setExportFormat(e.target.value as ExportFormatType)}
            className="form-radio text-blue-600"
          />
          <span>YAML</span>
        </label>
      </div>
    </div>
  );
};


function RepositoryExportFormatTooltip() {
  return <div>
    The format in which will be the models exported to Git. Also the diff editor shows the models in this format.
    <br/>
    &nbsp;- JSON is well-tested and the default for the rest of Dataspecer. Therefore, it is recommended.
    <br/>
    &nbsp;- YAML may be slightly more friendly for diff viewing experience. However, the implementation is experimental with no guarantee of being bug-free.
    <br/>
    (From a software perspective we are still working with JSON within Dataspecer, this format only affects the Git export and the diff editor)
  </div>;
}
