// Generated by ChatGPT from old UI and slightly modified

import { ResourceWithIris } from "@/package";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./ui/tooltip";
import { TooltipArrow } from "@radix-ui/react-tooltip";
import { useTranslation } from "react-i18next";

interface ResourceTooltipProps {
  resource: ResourceWithIris; // <-- replace this with your actual type
  side: "left" | "right";
  children: React.ReactNode;
}


export default function ResourceTooltip({ resource, side, children }: ResourceTooltipProps) {
  const { t } = useTranslation();

  return (
    <TooltipProvider delayDuration={80}>
      <Tooltip>
        <TooltipTrigger asChild>
          {children}
        </TooltipTrigger>

        <TooltipContent
          side={side}
        >
          <div>
            <strong>{t("git-tooltip.has-uncommitted-changes")}</strong>{" "}
            {resource.hasUncommittedChanges ? t("git-tooltip.yes") : t("git-tooltip.no")}
          </div>
          <div>
            <strong>{t("git-tooltip.active-merge-state-count")}</strong>{" "}
            {resource.activeMergeStateCount}
          </div>
          <div>
            <strong>{t("git-tooltip.project-iri")}</strong>{" "}
            {resource.projectIri}
          </div>
          <div>
            <strong>{resource.representsBranchHead ? t("git-tooltip.branch") : t("git-tooltip.commit")}</strong>
            : {resource.branch}
          </div>
          <div>
            <strong>{t("git-tooltip.type")}</strong>{" "}
            {resource.representsBranchHead ? t("git-tooltip.branch") : t("git-tooltip.commit")}
          </div>
          <div>
            <strong>{t("git-tooltip.tracked-commit-inside-dataspecer")}</strong>{" "}
            {resource.lastCommitHash.substring(0, 10)}
          </div>

          <TooltipArrow className="fill-black" />
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
