// Generated by ChatGPT from old UI and slightly modified

import { ResourceWithIris } from "@/package";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./ui/tooltip";
import { TooltipArrow } from "@radix-ui/react-tooltip";
import { useTranslation } from "react-i18next";

interface ResourceTooltipProps {
  resource: ResourceWithIris; // <-- replace this with your actual type
  side: "left" | "right";
  children: React.ReactNode;
  shouldBeOpen?: boolean;     // This prop is used for tour functionality - to open the tooltip even without pointing
}


export default function ResourceGitInfoTooltip({ resource, side, shouldBeOpen, children }: ResourceTooltipProps) {
  const { t } = useTranslation();

  return (
    <TooltipProvider delayDuration={80}>
      <Tooltip open={shouldBeOpen}>
        <TooltipTrigger asChild>
          {children}
        </TooltipTrigger>

        <TooltipContent
          id="git-tooltip-manager-all"
          side={side}
        >
          <div id="git-tooltip-manager-has-uncommitted-changes">
            <strong>{t("git-tooltip.has-uncommitted-changes")}</strong>{" "}
            {resource.hasUncommittedChanges ? t("git-tooltip.yes") : t("git-tooltip.no")}
          </div>
          <div id="git-tooltip-manager-active-merge-state-count">
            <strong>{t("git-tooltip.active-merge-state-count")}</strong>{" "}
            {resource.activeMergeStateCount}
          </div>
          <div id="git-tooltip-manager-project-iri">
            <strong>{t("git-tooltip.project-iri")}</strong>{" "}
            {resource.projectIri}
          </div>
          <div id="git-tooltip-manager-branch-or-commit">
            <strong>{resource.representsBranchHead ? t("git-tooltip.branch") : t("git-tooltip.commit")}</strong>
            : {resource.branch}
          </div>
          <div id="git-tooltip-manager-type">
            <strong>{t("git-tooltip.type")}</strong>{" "}
            {resource.representsBranchHead ? t("git-tooltip.branch") : t("git-tooltip.commit")}
          </div>
          <div id="git-tooltip-manager-tracked-commit-hash">
            <strong>{t("git-tooltip.tracked-commit-inside-dataspecer")}</strong>{" "}
            {resource.lastCommitHash.substring(0, 10)}
          </div>

          <TooltipArrow className="fill-black" />
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
