// Generated by ChatGPT from old UI and slightly modified

import { ResourceWithIris } from "@/package";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./ui/tooltip";
import { TooltipArrow } from "@radix-ui/react-tooltip";

interface ResourceTooltipProps {
  resource: ResourceWithIris; // <-- replace this with your actual type
  children: React.ReactNode;
}


export default function ResourceTooltip({ resource, children }: ResourceTooltipProps) {
  return (
    <TooltipProvider delayDuration={80}>
      <Tooltip>
        <TooltipTrigger asChild>
          {children}
        </TooltipTrigger>

        <TooltipContent
          side="right"
        >
          <div><strong>Has uncommited changes:</strong> {resource.hasUncommittedChanges ? "Yes" : "No" }</div>
          <div><strong>Active merge state count:</strong> {resource.activeMergeStateCount}</div>
          <div><strong>Project IRI:</strong> {resource.projectIri}</div>
          <div><strong>{resource.representsBranchHead ? "Branch" : "Commit"}:</strong> {resource.branch}</div>
          <div>
            <strong>Type:</strong>{" "}
            {resource.representsBranchHead ? "Branch" : "Commit"}
          </div>
          <div>
            <strong>Tracked commit inside Dataspecer:</strong> {resource.lastCommitHash.substring(0, 10)}
          </div>

          <TooltipArrow className="fill-black" />
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
