const SvgVisualDiff = (props: { mergeFromSvg: string, mergeToSvg: string }) => {
  return (
    <div className="flex h-screen">
      <SvgImage svgString={props.mergeFromSvg} />
      <div className="border-l border-gray-400" />
      <SvgImage svgString={props.mergeToSvg} />
    </div>
  );
};

/**
 * Core functionality generated by ChatGPT
 */
function SvgImage(props: { svgString: string }) {
  const encoded = encodeURIComponent(props.svgString)
    // Ensure proper XML/SVG encoding for special characters
    .replace(/'/g, "%27")
    .replace(/"/g, "%22");

  const dataUrl = `data:image/svg+xml,${encoded}`;

  return <div className="flex-1 overflow-auto p-2">
    <img src={dataUrl} alt="SVG" />
  </div>
}


/**
 * Generated by chatGPT
 * @deprecated TODO: Not used - I am not sure about this - I don't want to write sanitization - probably remove in favor of putting svg data into url and using <img>
 *
 */
// @ts-ignore
function SvgRenderer(props: { svgString: string }) {
  return (
    <div
      dangerouslySetInnerHTML={{ __html: props.svgString }}
    />
  );
}


export default SvgVisualDiff;
