import { z } from "zod";
import { asyncHandler } from "../utils/async-handler.ts";
import fs from "fs";
import express from "express";
import path from "path";

/**
 * Generated by ChatGPT
 */
function wrapPrivateKey(keyData: string, type: "RSA" | "OPENSSH" = "OPENSSH"): string {
  // Normalize: remove whitespace/newlines
  const cleanKey = keyData.replace(/\s+/g, "");

  // Split into 64-character lines (PEM standard)
  const formattedKey = cleanKey.match(/.{1,64}/g)?.join("\n") ?? cleanKey;

  // Not ChatGPT - but I notcited that it has to end with empty line
  return `-----BEGIN ${type} PRIVATE KEY-----\n${formattedKey}\n-----END ${type} PRIVATE KEY-----\n`;
}

const sshKeysRootDirectory = path.resolve("./ds-users/.ssh");
export const configPath = path.resolve(`${sshKeysRootDirectory}/config`);
export const configPathLinuxSeparators = path.resolve(`${sshKeysRootDirectory}/config`).replace(/\\/g, "/");


export const storePrivateSSHKey = asyncHandler(async (request: express.Request, response: express.Response) => {
  const bodySchema = z.object({
    privateSSHKey: z.string().min(1),
  });

  const authenticatedUser = response.locals.session?.user;
  if (authenticatedUser === undefined) {
    response.sendStatus(401);
    return;
  }

  const { privateSSHKey } = bodySchema.parse(request.body);

  const fileContent = wrapPrivateKey(privateSSHKey);

  fs.mkdirSync(sshKeysRootDirectory, {recursive: true});

  const userSSHIdentifer = createUserSSHIdentifier(authenticatedUser);
  const privateSSHKeyFilePath = path.normalize(`${sshKeysRootDirectory}/private-ssh-key-${userSSHIdentifer}`);
  fs.writeFileSync(privateSSHKeyFilePath, fileContent);

  // Hardcoded for github
  const newConfigEntry = `Host ${userSSHIdentifer}
    HostName github.com
    User git
    IdentityFile ${privateSSHKeyFilePath}\n\n`;

  fs.appendFileSync(configPath, newConfigEntry);

  response.status(200);
  return;
});


export const createUserSSHIdentifier = (authenticatedUser: any) => {
  const userSSHIdentifer = `${authenticatedUser.accountProvider}-${authenticatedUser.providerAccountId}`;
  return userSSHIdentifer;
};